set -g mouse on
set -g base-index 1
set -g focus-events on
set -g status-style 'bg=default fg=default'
setw -g mode-keys vi

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy'

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

run-shell 'tmux set-environment -g DOTFILES "$(dirname "$(dirname "$(readlink -f ~/.tmux.conf)")")"'

bind-key -r f run-shell 'tmux neww "$DOTFILES/bin/tmux-sessionizer"'

bind-key -r G run-shell '"$DOTFILES/bin/tmux-sessionizer" ~/Github'
bind-key -r C run-shell '"$DOTFILES/bin/tmux-sessionizer" ~/College'
bind-key -r O run-shell '"$DOTFILES/bin/tmux-sessionizer" ~/Codes'
bind-key -r D run-shell '"$DOTFILES/bin/tmux-sessionizer" ~/Downloads'
bind-key -r H run-shell '"$DOTFILES/bin/tmux-sessionizer" "$DOTFILES"'
bind-key -r L run-shell '"$DOTFILES/bin/tmux-sessionizer" ~/LBYARCH'

%hidden HOPES_POPUP="display-popup -E -w 75% -h 75% $HOME/.cargo/bin/hopes"
bind-key t $HOPES_POPUP
bind-key T $HOPES_POPUP
